/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConviteTokenRouteImport } from './routes/convite.$token'
import { Route as BriefingClientIdRouteImport } from './routes/briefing.$clientId'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedReunioesRouteImport } from './routes/_authenticated/reunioes'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedNotificacoesRouteImport } from './routes/_authenticated/notificacoes'
import { Route as AuthenticatedMinhaJornadaRouteImport } from './routes/_authenticated/minha-jornada'
import { Route as AuthenticatedMeuPerfilRouteImport } from './routes/_authenticated/meu-perfil'
import { Route as AuthenticatedJovensRouteImport } from './routes/_authenticated/jovens'
import { Route as AuthenticatedJornadaRouteImport } from './routes/_authenticated/jornada'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedServicosIndexRouteImport } from './routes/_authenticated/servicos.index'
import { Route as AuthenticatedReunioesIndexRouteImport } from './routes/_authenticated/reunioes.index'
import { Route as AuthenticatedJovensIndexRouteImport } from './routes/_authenticated/jovens.index'
import { Route as AuthenticatedCrmIndexRouteImport } from './routes/_authenticated/crm.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedServicosIdRouteImport } from './routes/_authenticated/servicos.$id'
import { Route as AuthenticatedReunioesIdRouteImport } from './routes/_authenticated/reunioes.$id'
import { Route as AuthenticatedJovensInscricoesRouteImport } from './routes/_authenticated/jovens.inscricoes'
import { Route as AuthenticatedJovensIdRouteImport } from './routes/_authenticated/jovens.$id'
import { Route as AuthenticatedCrmListaRouteImport } from './routes/_authenticated/crm.lista'
import { Route as AuthenticatedCrmIdRouteImport } from './routes/_authenticated/crm.$id'
import { Route as AuthenticatedClientesIdRouteImport } from './routes/_authenticated/clientes.$id'
import { Route as AuthenticatedAdminQuizzesRouteImport } from './routes/_authenticated/admin.quizzes'
import { Route as AuthenticatedJovensIdJornadaRouteImport } from './routes/_authenticated/jovens.$id.jornada'
import { Route as AuthenticatedJornadaQuizPhaseIdRouteImport } from './routes/_authenticated/jornada.quiz.$phaseId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConviteTokenRoute = ConviteTokenRouteImport.update({
  id: '/convite/$token',
  path: '/convite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefingClientIdRoute = BriefingClientIdRouteImport.update({
  id: '/briefing/$clientId',
  path: '/briefing/$clientId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReunioesRoute = AuthenticatedReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedNotificacoesRoute =
  AuthenticatedNotificacoesRouteImport.update({
    id: '/notificacoes',
    path: '/notificacoes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMinhaJornadaRoute =
  AuthenticatedMinhaJornadaRouteImport.update({
    id: '/minha-jornada',
    path: '/minha-jornada',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMeuPerfilRoute = AuthenticatedMeuPerfilRouteImport.update({
  id: '/meu-perfil',
  path: '/meu-perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJovensRoute = AuthenticatedJovensRouteImport.update({
  id: '/jovens',
  path: '/jovens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJornadaRoute = AuthenticatedJornadaRouteImport.update({
  id: '/jornada',
  path: '/jornada',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicosIndexRoute =
  AuthenticatedServicosIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedServicosRoute,
  } as any)
const AuthenticatedReunioesIndexRoute =
  AuthenticatedReunioesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedReunioesRoute,
  } as any)
const AuthenticatedJovensIndexRoute =
  AuthenticatedJovensIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedJovensRoute,
  } as any)
const AuthenticatedCrmIndexRoute = AuthenticatedCrmIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedServicosIdRoute = AuthenticatedServicosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedServicosRoute,
} as any)
const AuthenticatedReunioesIdRoute = AuthenticatedReunioesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedReunioesRoute,
} as any)
const AuthenticatedJovensInscricoesRoute =
  AuthenticatedJovensInscricoesRouteImport.update({
    id: '/inscricoes',
    path: '/inscricoes',
    getParentRoute: () => AuthenticatedJovensRoute,
  } as any)
const AuthenticatedJovensIdRoute = AuthenticatedJovensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedJovensRoute,
} as any)
const AuthenticatedCrmListaRoute = AuthenticatedCrmListaRouteImport.update({
  id: '/lista',
  path: '/lista',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedCrmIdRoute = AuthenticatedCrmIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedCrmRoute,
} as any)
const AuthenticatedClientesIdRoute = AuthenticatedClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedClientesRoute,
} as any)
const AuthenticatedAdminQuizzesRoute =
  AuthenticatedAdminQuizzesRouteImport.update({
    id: '/admin/quizzes',
    path: '/admin/quizzes',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedJovensIdJornadaRoute =
  AuthenticatedJovensIdJornadaRouteImport.update({
    id: '/jornada',
    path: '/jornada',
    getParentRoute: () => AuthenticatedJovensIdRoute,
  } as any)
const AuthenticatedJornadaQuizPhaseIdRoute =
  AuthenticatedJornadaQuizPhaseIdRouteImport.update({
    id: '/quiz/$phaseId',
    path: '/quiz/$phaseId',
    getParentRoute: () => AuthenticatedJornadaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/crm': typeof AuthenticatedCrmRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/jornada': typeof AuthenticatedJornadaRouteWithChildren
  '/jovens': typeof AuthenticatedJovensRouteWithChildren
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/minha-jornada': typeof AuthenticatedMinhaJornadaRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/reunioes': typeof AuthenticatedReunioesRouteWithChildren
  '/servicos': typeof AuthenticatedServicosRouteWithChildren
  '/settings': typeof AuthenticatedSettingsRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/users': typeof AuthenticatedUsersRoute
  '/briefing/$clientId': typeof BriefingClientIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/crm/lista': typeof AuthenticatedCrmListaRoute
  '/jovens/$id': typeof AuthenticatedJovensIdRouteWithChildren
  '/jovens/inscricoes': typeof AuthenticatedJovensInscricoesRoute
  '/reunioes/$id': typeof AuthenticatedReunioesIdRoute
  '/servicos/$id': typeof AuthenticatedServicosIdRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/crm/': typeof AuthenticatedCrmIndexRoute
  '/jovens/': typeof AuthenticatedJovensIndexRoute
  '/reunioes/': typeof AuthenticatedReunioesIndexRoute
  '/servicos/': typeof AuthenticatedServicosIndexRoute
  '/jornada/quiz/$phaseId': typeof AuthenticatedJornadaQuizPhaseIdRoute
  '/jovens/$id/jornada': typeof AuthenticatedJovensIdJornadaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/jornada': typeof AuthenticatedJornadaRouteWithChildren
  '/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/minha-jornada': typeof AuthenticatedMinhaJornadaRoute
  '/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/users': typeof AuthenticatedUsersRoute
  '/briefing/$clientId': typeof BriefingClientIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/crm/$id': typeof AuthenticatedCrmIdRoute
  '/crm/lista': typeof AuthenticatedCrmListaRoute
  '/jovens/$id': typeof AuthenticatedJovensIdRouteWithChildren
  '/jovens/inscricoes': typeof AuthenticatedJovensInscricoesRoute
  '/reunioes/$id': typeof AuthenticatedReunioesIdRoute
  '/servicos/$id': typeof AuthenticatedServicosIdRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/crm': typeof AuthenticatedCrmIndexRoute
  '/jovens': typeof AuthenticatedJovensIndexRoute
  '/reunioes': typeof AuthenticatedReunioesIndexRoute
  '/servicos': typeof AuthenticatedServicosIndexRoute
  '/jornada/quiz/$phaseId': typeof AuthenticatedJornadaQuizPhaseIdRoute
  '/jovens/$id/jornada': typeof AuthenticatedJovensIdJornadaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/crm': typeof AuthenticatedCrmRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/jornada': typeof AuthenticatedJornadaRouteWithChildren
  '/_authenticated/jovens': typeof AuthenticatedJovensRouteWithChildren
  '/_authenticated/meu-perfil': typeof AuthenticatedMeuPerfilRoute
  '/_authenticated/minha-jornada': typeof AuthenticatedMinhaJornadaRoute
  '/_authenticated/notificacoes': typeof AuthenticatedNotificacoesRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/reunioes': typeof AuthenticatedReunioesRouteWithChildren
  '/_authenticated/servicos': typeof AuthenticatedServicosRouteWithChildren
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/briefing/$clientId': typeof BriefingClientIdRoute
  '/convite/$token': typeof ConviteTokenRoute
  '/_authenticated/admin/quizzes': typeof AuthenticatedAdminQuizzesRoute
  '/_authenticated/clientes/$id': typeof AuthenticatedClientesIdRoute
  '/_authenticated/crm/$id': typeof AuthenticatedCrmIdRoute
  '/_authenticated/crm/lista': typeof AuthenticatedCrmListaRoute
  '/_authenticated/jovens/$id': typeof AuthenticatedJovensIdRouteWithChildren
  '/_authenticated/jovens/inscricoes': typeof AuthenticatedJovensInscricoesRoute
  '/_authenticated/reunioes/$id': typeof AuthenticatedReunioesIdRoute
  '/_authenticated/servicos/$id': typeof AuthenticatedServicosIdRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/crm/': typeof AuthenticatedCrmIndexRoute
  '/_authenticated/jovens/': typeof AuthenticatedJovensIndexRoute
  '/_authenticated/reunioes/': typeof AuthenticatedReunioesIndexRoute
  '/_authenticated/servicos/': typeof AuthenticatedServicosIndexRoute
  '/_authenticated/jornada/quiz/$phaseId': typeof AuthenticatedJornadaQuizPhaseIdRoute
  '/_authenticated/jovens/$id/jornada': typeof AuthenticatedJovensIdJornadaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/reset-password'
    | '/clientes'
    | '/crm'
    | '/dashboard'
    | '/indicadores'
    | '/jornada'
    | '/jovens'
    | '/meu-perfil'
    | '/minha-jornada'
    | '/notificacoes'
    | '/perfil'
    | '/reunioes'
    | '/servicos'
    | '/settings'
    | '/tarefas'
    | '/users'
    | '/briefing/$clientId'
    | '/convite/$token'
    | '/admin/quizzes'
    | '/clientes/$id'
    | '/crm/$id'
    | '/crm/lista'
    | '/jovens/$id'
    | '/jovens/inscricoes'
    | '/reunioes/$id'
    | '/servicos/$id'
    | '/clientes/'
    | '/crm/'
    | '/jovens/'
    | '/reunioes/'
    | '/servicos/'
    | '/jornada/quiz/$phaseId'
    | '/jovens/$id/jornada'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/reset-password'
    | '/dashboard'
    | '/indicadores'
    | '/jornada'
    | '/meu-perfil'
    | '/minha-jornada'
    | '/notificacoes'
    | '/perfil'
    | '/settings'
    | '/tarefas'
    | '/users'
    | '/briefing/$clientId'
    | '/convite/$token'
    | '/admin/quizzes'
    | '/clientes/$id'
    | '/crm/$id'
    | '/crm/lista'
    | '/jovens/$id'
    | '/jovens/inscricoes'
    | '/reunioes/$id'
    | '/servicos/$id'
    | '/clientes'
    | '/crm'
    | '/jovens'
    | '/reunioes'
    | '/servicos'
    | '/jornada/quiz/$phaseId'
    | '/jovens/$id/jornada'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/reset-password'
    | '/_authenticated/clientes'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/indicadores'
    | '/_authenticated/jornada'
    | '/_authenticated/jovens'
    | '/_authenticated/meu-perfil'
    | '/_authenticated/minha-jornada'
    | '/_authenticated/notificacoes'
    | '/_authenticated/perfil'
    | '/_authenticated/reunioes'
    | '/_authenticated/servicos'
    | '/_authenticated/settings'
    | '/_authenticated/tarefas'
    | '/_authenticated/users'
    | '/briefing/$clientId'
    | '/convite/$token'
    | '/_authenticated/admin/quizzes'
    | '/_authenticated/clientes/$id'
    | '/_authenticated/crm/$id'
    | '/_authenticated/crm/lista'
    | '/_authenticated/jovens/$id'
    | '/_authenticated/jovens/inscricoes'
    | '/_authenticated/reunioes/$id'
    | '/_authenticated/servicos/$id'
    | '/_authenticated/clientes/'
    | '/_authenticated/crm/'
    | '/_authenticated/jovens/'
    | '/_authenticated/reunioes/'
    | '/_authenticated/servicos/'
    | '/_authenticated/jornada/quiz/$phaseId'
    | '/_authenticated/jovens/$id/jornada'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InscricaoRoute: typeof InscricaoRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  BriefingClientIdRoute: typeof BriefingClientIdRoute
  ConviteTokenRoute: typeof ConviteTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/convite/$token': {
      id: '/convite/$token'
      path: '/convite/$token'
      fullPath: '/convite/$token'
      preLoaderRoute: typeof ConviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/briefing/$clientId': {
      id: '/briefing/$clientId'
      path: '/briefing/$clientId'
      fullPath: '/briefing/$clientId'
      preLoaderRoute: typeof BriefingClientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reunioes': {
      id: '/_authenticated/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof AuthenticatedReunioesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notificacoes': {
      id: '/_authenticated/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof AuthenticatedNotificacoesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/minha-jornada': {
      id: '/_authenticated/minha-jornada'
      path: '/minha-jornada'
      fullPath: '/minha-jornada'
      preLoaderRoute: typeof AuthenticatedMinhaJornadaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/meu-perfil': {
      id: '/_authenticated/meu-perfil'
      path: '/meu-perfil'
      fullPath: '/meu-perfil'
      preLoaderRoute: typeof AuthenticatedMeuPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jovens': {
      id: '/_authenticated/jovens'
      path: '/jovens'
      fullPath: '/jovens'
      preLoaderRoute: typeof AuthenticatedJovensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jornada': {
      id: '/_authenticated/jornada'
      path: '/jornada'
      fullPath: '/jornada'
      preLoaderRoute: typeof AuthenticatedJornadaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servicos/': {
      id: '/_authenticated/servicos/'
      path: '/'
      fullPath: '/servicos/'
      preLoaderRoute: typeof AuthenticatedServicosIndexRouteImport
      parentRoute: typeof AuthenticatedServicosRoute
    }
    '/_authenticated/reunioes/': {
      id: '/_authenticated/reunioes/'
      path: '/'
      fullPath: '/reunioes/'
      preLoaderRoute: typeof AuthenticatedReunioesIndexRouteImport
      parentRoute: typeof AuthenticatedReunioesRoute
    }
    '/_authenticated/jovens/': {
      id: '/_authenticated/jovens/'
      path: '/'
      fullPath: '/jovens/'
      preLoaderRoute: typeof AuthenticatedJovensIndexRouteImport
      parentRoute: typeof AuthenticatedJovensRoute
    }
    '/_authenticated/crm/': {
      id: '/_authenticated/crm/'
      path: '/'
      fullPath: '/crm/'
      preLoaderRoute: typeof AuthenticatedCrmIndexRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/servicos/$id': {
      id: '/_authenticated/servicos/$id'
      path: '/$id'
      fullPath: '/servicos/$id'
      preLoaderRoute: typeof AuthenticatedServicosIdRouteImport
      parentRoute: typeof AuthenticatedServicosRoute
    }
    '/_authenticated/reunioes/$id': {
      id: '/_authenticated/reunioes/$id'
      path: '/$id'
      fullPath: '/reunioes/$id'
      preLoaderRoute: typeof AuthenticatedReunioesIdRouteImport
      parentRoute: typeof AuthenticatedReunioesRoute
    }
    '/_authenticated/jovens/inscricoes': {
      id: '/_authenticated/jovens/inscricoes'
      path: '/inscricoes'
      fullPath: '/jovens/inscricoes'
      preLoaderRoute: typeof AuthenticatedJovensInscricoesRouteImport
      parentRoute: typeof AuthenticatedJovensRoute
    }
    '/_authenticated/jovens/$id': {
      id: '/_authenticated/jovens/$id'
      path: '/$id'
      fullPath: '/jovens/$id'
      preLoaderRoute: typeof AuthenticatedJovensIdRouteImport
      parentRoute: typeof AuthenticatedJovensRoute
    }
    '/_authenticated/crm/lista': {
      id: '/_authenticated/crm/lista'
      path: '/lista'
      fullPath: '/crm/lista'
      preLoaderRoute: typeof AuthenticatedCrmListaRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/crm/$id': {
      id: '/_authenticated/crm/$id'
      path: '/$id'
      fullPath: '/crm/$id'
      preLoaderRoute: typeof AuthenticatedCrmIdRouteImport
      parentRoute: typeof AuthenticatedCrmRoute
    }
    '/_authenticated/clientes/$id': {
      id: '/_authenticated/clientes/$id'
      path: '/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof AuthenticatedClientesIdRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/admin/quizzes': {
      id: '/_authenticated/admin/quizzes'
      path: '/admin/quizzes'
      fullPath: '/admin/quizzes'
      preLoaderRoute: typeof AuthenticatedAdminQuizzesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jovens/$id/jornada': {
      id: '/_authenticated/jovens/$id/jornada'
      path: '/jornada'
      fullPath: '/jovens/$id/jornada'
      preLoaderRoute: typeof AuthenticatedJovensIdJornadaRouteImport
      parentRoute: typeof AuthenticatedJovensIdRoute
    }
    '/_authenticated/jornada/quiz/$phaseId': {
      id: '/_authenticated/jornada/quiz/$phaseId'
      path: '/quiz/$phaseId'
      fullPath: '/jornada/quiz/$phaseId'
      preLoaderRoute: typeof AuthenticatedJornadaQuizPhaseIdRouteImport
      parentRoute: typeof AuthenticatedJornadaRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIdRoute: typeof AuthenticatedClientesIdRoute
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIdRoute: AuthenticatedClientesIdRoute,
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedCrmRouteChildren {
  AuthenticatedCrmIdRoute: typeof AuthenticatedCrmIdRoute
  AuthenticatedCrmListaRoute: typeof AuthenticatedCrmListaRoute
  AuthenticatedCrmIndexRoute: typeof AuthenticatedCrmIndexRoute
}

const AuthenticatedCrmRouteChildren: AuthenticatedCrmRouteChildren = {
  AuthenticatedCrmIdRoute: AuthenticatedCrmIdRoute,
  AuthenticatedCrmListaRoute: AuthenticatedCrmListaRoute,
  AuthenticatedCrmIndexRoute: AuthenticatedCrmIndexRoute,
}

const AuthenticatedCrmRouteWithChildren =
  AuthenticatedCrmRoute._addFileChildren(AuthenticatedCrmRouteChildren)

interface AuthenticatedJornadaRouteChildren {
  AuthenticatedJornadaQuizPhaseIdRoute: typeof AuthenticatedJornadaQuizPhaseIdRoute
}

const AuthenticatedJornadaRouteChildren: AuthenticatedJornadaRouteChildren = {
  AuthenticatedJornadaQuizPhaseIdRoute: AuthenticatedJornadaQuizPhaseIdRoute,
}

const AuthenticatedJornadaRouteWithChildren =
  AuthenticatedJornadaRoute._addFileChildren(AuthenticatedJornadaRouteChildren)

interface AuthenticatedJovensIdRouteChildren {
  AuthenticatedJovensIdJornadaRoute: typeof AuthenticatedJovensIdJornadaRoute
}

const AuthenticatedJovensIdRouteChildren: AuthenticatedJovensIdRouteChildren = {
  AuthenticatedJovensIdJornadaRoute: AuthenticatedJovensIdJornadaRoute,
}

const AuthenticatedJovensIdRouteWithChildren =
  AuthenticatedJovensIdRoute._addFileChildren(
    AuthenticatedJovensIdRouteChildren,
  )

interface AuthenticatedJovensRouteChildren {
  AuthenticatedJovensIdRoute: typeof AuthenticatedJovensIdRouteWithChildren
  AuthenticatedJovensInscricoesRoute: typeof AuthenticatedJovensInscricoesRoute
  AuthenticatedJovensIndexRoute: typeof AuthenticatedJovensIndexRoute
}

const AuthenticatedJovensRouteChildren: AuthenticatedJovensRouteChildren = {
  AuthenticatedJovensIdRoute: AuthenticatedJovensIdRouteWithChildren,
  AuthenticatedJovensInscricoesRoute: AuthenticatedJovensInscricoesRoute,
  AuthenticatedJovensIndexRoute: AuthenticatedJovensIndexRoute,
}

const AuthenticatedJovensRouteWithChildren =
  AuthenticatedJovensRoute._addFileChildren(AuthenticatedJovensRouteChildren)

interface AuthenticatedReunioesRouteChildren {
  AuthenticatedReunioesIdRoute: typeof AuthenticatedReunioesIdRoute
  AuthenticatedReunioesIndexRoute: typeof AuthenticatedReunioesIndexRoute
}

const AuthenticatedReunioesRouteChildren: AuthenticatedReunioesRouteChildren = {
  AuthenticatedReunioesIdRoute: AuthenticatedReunioesIdRoute,
  AuthenticatedReunioesIndexRoute: AuthenticatedReunioesIndexRoute,
}

const AuthenticatedReunioesRouteWithChildren =
  AuthenticatedReunioesRoute._addFileChildren(
    AuthenticatedReunioesRouteChildren,
  )

interface AuthenticatedServicosRouteChildren {
  AuthenticatedServicosIdRoute: typeof AuthenticatedServicosIdRoute
  AuthenticatedServicosIndexRoute: typeof AuthenticatedServicosIndexRoute
}

const AuthenticatedServicosRouteChildren: AuthenticatedServicosRouteChildren = {
  AuthenticatedServicosIdRoute: AuthenticatedServicosIdRoute,
  AuthenticatedServicosIndexRoute: AuthenticatedServicosIndexRoute,
}

const AuthenticatedServicosRouteWithChildren =
  AuthenticatedServicosRoute._addFileChildren(
    AuthenticatedServicosRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedJornadaRoute: typeof AuthenticatedJornadaRouteWithChildren
  AuthenticatedJovensRoute: typeof AuthenticatedJovensRouteWithChildren
  AuthenticatedMeuPerfilRoute: typeof AuthenticatedMeuPerfilRoute
  AuthenticatedMinhaJornadaRoute: typeof AuthenticatedMinhaJornadaRoute
  AuthenticatedNotificacoesRoute: typeof AuthenticatedNotificacoesRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedReunioesRoute: typeof AuthenticatedReunioesRouteWithChildren
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRouteWithChildren
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
  AuthenticatedAdminQuizzesRoute: typeof AuthenticatedAdminQuizzesRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedCrmRoute: AuthenticatedCrmRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedJornadaRoute: AuthenticatedJornadaRouteWithChildren,
  AuthenticatedJovensRoute: AuthenticatedJovensRouteWithChildren,
  AuthenticatedMeuPerfilRoute: AuthenticatedMeuPerfilRoute,
  AuthenticatedMinhaJornadaRoute: AuthenticatedMinhaJornadaRoute,
  AuthenticatedNotificacoesRoute: AuthenticatedNotificacoesRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedReunioesRoute: AuthenticatedReunioesRouteWithChildren,
  AuthenticatedServicosRoute: AuthenticatedServicosRouteWithChildren,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
  AuthenticatedAdminQuizzesRoute: AuthenticatedAdminQuizzesRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InscricaoRoute: InscricaoRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  BriefingClientIdRoute: BriefingClientIdRoute,
  ConviteTokenRoute: ConviteTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
