/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InscricaoRouteImport } from './routes/inscricao'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedUsersRouteImport } from './routes/_authenticated/users'
import { Route as AuthenticatedTarefasRouteImport } from './routes/_authenticated/tarefas'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedServicosRouteImport } from './routes/_authenticated/servicos'
import { Route as AuthenticatedReunioesRouteImport } from './routes/_authenticated/reunioes'
import { Route as AuthenticatedJovensRouteImport } from './routes/_authenticated/jovens'
import { Route as AuthenticatedIndicadoresRouteImport } from './routes/_authenticated/indicadores'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated/crm'
import { Route as AuthenticatedClientesRouteImport } from './routes/_authenticated/clientes'
import { Route as AuthenticatedJovensIndexRouteImport } from './routes/_authenticated/jovens.index'
import { Route as AuthenticatedClientesIndexRouteImport } from './routes/_authenticated/clientes.index'
import { Route as AuthenticatedJovensInscricoesRouteImport } from './routes/_authenticated/jovens.inscricoes'
import { Route as AuthenticatedJovensIdRouteImport } from './routes/_authenticated/jovens.$id'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InscricaoRoute = InscricaoRouteImport.update({
  id: '/inscricao',
  path: '/inscricao',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedUsersRoute = AuthenticatedUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTarefasRoute = AuthenticatedTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedServicosRoute = AuthenticatedServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedReunioesRoute = AuthenticatedReunioesRouteImport.update({
  id: '/reunioes',
  path: '/reunioes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJovensRoute = AuthenticatedJovensRouteImport.update({
  id: '/jovens',
  path: '/jovens',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedIndicadoresRoute =
  AuthenticatedIndicadoresRouteImport.update({
    id: '/indicadores',
    path: '/indicadores',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientesRoute = AuthenticatedClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedJovensIndexRoute =
  AuthenticatedJovensIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedJovensRoute,
  } as any)
const AuthenticatedClientesIndexRoute =
  AuthenticatedClientesIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedClientesRoute,
  } as any)
const AuthenticatedJovensInscricoesRoute =
  AuthenticatedJovensInscricoesRouteImport.update({
    id: '/inscricoes',
    path: '/inscricoes',
    getParentRoute: () => AuthenticatedJovensRoute,
  } as any)
const AuthenticatedJovensIdRoute = AuthenticatedJovensIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AuthenticatedJovensRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/jovens': typeof AuthenticatedJovensRouteWithChildren
  '/reunioes': typeof AuthenticatedReunioesRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/users': typeof AuthenticatedUsersRoute
  '/jovens/$id': typeof AuthenticatedJovensIdRoute
  '/jovens/inscricoes': typeof AuthenticatedJovensInscricoesRoute
  '/clientes/': typeof AuthenticatedClientesIndexRoute
  '/jovens/': typeof AuthenticatedJovensIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/indicadores': typeof AuthenticatedIndicadoresRoute
  '/reunioes': typeof AuthenticatedReunioesRoute
  '/servicos': typeof AuthenticatedServicosRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/tarefas': typeof AuthenticatedTarefasRoute
  '/users': typeof AuthenticatedUsersRoute
  '/jovens/$id': typeof AuthenticatedJovensIdRoute
  '/jovens/inscricoes': typeof AuthenticatedJovensInscricoesRoute
  '/clientes': typeof AuthenticatedClientesIndexRoute
  '/jovens': typeof AuthenticatedJovensIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/inscricao': typeof InscricaoRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/clientes': typeof AuthenticatedClientesRouteWithChildren
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/indicadores': typeof AuthenticatedIndicadoresRoute
  '/_authenticated/jovens': typeof AuthenticatedJovensRouteWithChildren
  '/_authenticated/reunioes': typeof AuthenticatedReunioesRoute
  '/_authenticated/servicos': typeof AuthenticatedServicosRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/tarefas': typeof AuthenticatedTarefasRoute
  '/_authenticated/users': typeof AuthenticatedUsersRoute
  '/_authenticated/jovens/$id': typeof AuthenticatedJovensIdRoute
  '/_authenticated/jovens/inscricoes': typeof AuthenticatedJovensInscricoesRoute
  '/_authenticated/clientes/': typeof AuthenticatedClientesIndexRoute
  '/_authenticated/jovens/': typeof AuthenticatedJovensIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/reset-password'
    | '/clientes'
    | '/crm'
    | '/dashboard'
    | '/indicadores'
    | '/jovens'
    | '/reunioes'
    | '/servicos'
    | '/settings'
    | '/tarefas'
    | '/users'
    | '/jovens/$id'
    | '/jovens/inscricoes'
    | '/clientes/'
    | '/jovens/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/reset-password'
    | '/crm'
    | '/dashboard'
    | '/indicadores'
    | '/reunioes'
    | '/servicos'
    | '/settings'
    | '/tarefas'
    | '/users'
    | '/jovens/$id'
    | '/jovens/inscricoes'
    | '/clientes'
    | '/jovens'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/inscricao'
    | '/login'
    | '/reset-password'
    | '/_authenticated/clientes'
    | '/_authenticated/crm'
    | '/_authenticated/dashboard'
    | '/_authenticated/indicadores'
    | '/_authenticated/jovens'
    | '/_authenticated/reunioes'
    | '/_authenticated/servicos'
    | '/_authenticated/settings'
    | '/_authenticated/tarefas'
    | '/_authenticated/users'
    | '/_authenticated/jovens/$id'
    | '/_authenticated/jovens/inscricoes'
    | '/_authenticated/clientes/'
    | '/_authenticated/jovens/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InscricaoRoute: typeof InscricaoRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscricao': {
      id: '/inscricao'
      path: '/inscricao'
      fullPath: '/inscricao'
      preLoaderRoute: typeof InscricaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/users': {
      id: '/_authenticated/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AuthenticatedUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/tarefas': {
      id: '/_authenticated/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof AuthenticatedTarefasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/servicos': {
      id: '/_authenticated/servicos'
      path: '/servicos'
      fullPath: '/servicos'
      preLoaderRoute: typeof AuthenticatedServicosRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/reunioes': {
      id: '/_authenticated/reunioes'
      path: '/reunioes'
      fullPath: '/reunioes'
      preLoaderRoute: typeof AuthenticatedReunioesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jovens': {
      id: '/_authenticated/jovens'
      path: '/jovens'
      fullPath: '/jovens'
      preLoaderRoute: typeof AuthenticatedJovensRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/indicadores': {
      id: '/_authenticated/indicadores'
      path: '/indicadores'
      fullPath: '/indicadores'
      preLoaderRoute: typeof AuthenticatedIndicadoresRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clientes': {
      id: '/_authenticated/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof AuthenticatedClientesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/jovens/': {
      id: '/_authenticated/jovens/'
      path: '/'
      fullPath: '/jovens/'
      preLoaderRoute: typeof AuthenticatedJovensIndexRouteImport
      parentRoute: typeof AuthenticatedJovensRoute
    }
    '/_authenticated/clientes/': {
      id: '/_authenticated/clientes/'
      path: '/'
      fullPath: '/clientes/'
      preLoaderRoute: typeof AuthenticatedClientesIndexRouteImport
      parentRoute: typeof AuthenticatedClientesRoute
    }
    '/_authenticated/jovens/inscricoes': {
      id: '/_authenticated/jovens/inscricoes'
      path: '/inscricoes'
      fullPath: '/jovens/inscricoes'
      preLoaderRoute: typeof AuthenticatedJovensInscricoesRouteImport
      parentRoute: typeof AuthenticatedJovensRoute
    }
    '/_authenticated/jovens/$id': {
      id: '/_authenticated/jovens/$id'
      path: '/$id'
      fullPath: '/jovens/$id'
      preLoaderRoute: typeof AuthenticatedJovensIdRouteImport
      parentRoute: typeof AuthenticatedJovensRoute
    }
  }
}

interface AuthenticatedClientesRouteChildren {
  AuthenticatedClientesIndexRoute: typeof AuthenticatedClientesIndexRoute
}

const AuthenticatedClientesRouteChildren: AuthenticatedClientesRouteChildren = {
  AuthenticatedClientesIndexRoute: AuthenticatedClientesIndexRoute,
}

const AuthenticatedClientesRouteWithChildren =
  AuthenticatedClientesRoute._addFileChildren(
    AuthenticatedClientesRouteChildren,
  )

interface AuthenticatedJovensRouteChildren {
  AuthenticatedJovensIdRoute: typeof AuthenticatedJovensIdRoute
  AuthenticatedJovensInscricoesRoute: typeof AuthenticatedJovensInscricoesRoute
  AuthenticatedJovensIndexRoute: typeof AuthenticatedJovensIndexRoute
}

const AuthenticatedJovensRouteChildren: AuthenticatedJovensRouteChildren = {
  AuthenticatedJovensIdRoute: AuthenticatedJovensIdRoute,
  AuthenticatedJovensInscricoesRoute: AuthenticatedJovensInscricoesRoute,
  AuthenticatedJovensIndexRoute: AuthenticatedJovensIndexRoute,
}

const AuthenticatedJovensRouteWithChildren =
  AuthenticatedJovensRoute._addFileChildren(AuthenticatedJovensRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedClientesRoute: typeof AuthenticatedClientesRouteWithChildren
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedIndicadoresRoute: typeof AuthenticatedIndicadoresRoute
  AuthenticatedJovensRoute: typeof AuthenticatedJovensRouteWithChildren
  AuthenticatedReunioesRoute: typeof AuthenticatedReunioesRoute
  AuthenticatedServicosRoute: typeof AuthenticatedServicosRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedTarefasRoute: typeof AuthenticatedTarefasRoute
  AuthenticatedUsersRoute: typeof AuthenticatedUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedClientesRoute: AuthenticatedClientesRouteWithChildren,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedIndicadoresRoute: AuthenticatedIndicadoresRoute,
  AuthenticatedJovensRoute: AuthenticatedJovensRouteWithChildren,
  AuthenticatedReunioesRoute: AuthenticatedReunioesRoute,
  AuthenticatedServicosRoute: AuthenticatedServicosRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedTarefasRoute: AuthenticatedTarefasRoute,
  AuthenticatedUsersRoute: AuthenticatedUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InscricaoRoute: InscricaoRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
